DOMAIN = "home-ems"

CONF_NAME = "home-ems"
CONF_ENTITY_ID = "home_ems"

CONF_MAX_POWER_PER_PHASE = 6000
CONF_MAX_CURRENT_PER_PHASE = 25

CONF_WATER_HEATER_MIN_TEMP = 50
CONF_WATER_HEATER_MAX_TEMP = 62

# External IDs
CONF_WATER_HEATER_ID = "chauffe_eau"
CONF_LINKY_ID = "tic"
CONF_ENHPASE_ID = "enphase"
CONF_EV_CHARGER_ID = "charger"
CONF_CRO_ID = "cro"
CONF_POOL_ID = "pipool"

# Electrical config
CONF_POOL_HEATER_PHASE = 1 << 1

CONF_WATER_HEATER_PHASE = 1 << 2
CONF_WATER_HEATER_MIN_POWER = 650
CONF_WATER_HEATER_MAX_POWER = 1000 # 2450 is real value with electrical resistance but it is rarely used

CONF_EV_CHARGER_PHASE_MONO = 1 << 0
CONF_EV_CHARGER_MIN_POWER = 1500
CONF_EV_CHARGER_MIN_DELTA = 200

CONF_CRO_POWER = 2500
CONF_CRO_PHASE = 1 << 2
CONF_CRO_MIN_DELTA = 200

# Load balancer timings
CONF_CRO_WAITING_TIME = 1
CONF_EV_CHARGER_WAITING_TIME = 3
CONF_WATER_HEATER_WAITING_TIME = 1
CONF_POOL_HEATER_WAITING_TIME = 2