DOMAIN = "home-ems"

CONF_NAME = "home-ems"
CONF_ENTITY_ID = "home_ems"

CONF_PROD = False

CONF_MAX_CURRENT_PER_PHASE = 25

CONF_WATER_HEATER_MIN_TEMP = 50
CONF_WATER_HEATER_MAX_TEMP = 62

# External IDs
CONF_WATER_HEATER_ID = "chauffe_eau"
CONF_WATER_HEATER_ALLOW_RESISTOR_ID = "switch.allow_resistor"
CONF_LINKY_ID = "tic"
CONF_EV_CHARGER_ID = "charger"

CONF_POOL_ID = "pipool"

# Electrical config
CONF_POOL_HEATER_PHASE = 1 << 0
CONF_WATER_HEATER_PHASE = 1 << 2
CONF_EV_CHARGER_PHASE_MONO = 1 << 0
CONF_EV_CHARGER_MIN_CURRENT = 6
